server:
  port: 7766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7766/eureka/
    #设置成true(默认值true),Eureka client在启动时会从Eureka server获取注册信息并缓存到本地,之后只会增量获取信息
    fetch-registry: false
    #是否将微服务本身注册到注册中心(集群环境下开启true)
    register-with-eureka: false
    #缓存清单的默认更新时间（单位：s）
    registry-fetch-interval-seconds: 30
  instance:
    #服务续约的调用时间（单位：s）
    lease-renewal-interval-in-seconds: 30
    #服务失效时间（单位：s）
    lease-expiration-duration-in-seconds: 90
  server:
    #是否开启注册中心的自我保护（默认：true）
    enable-self-preservation: true
spring:
  application:
    #注册中心实例名称
    name: dm-eureka-server